#r1.0.2
#
# BCM56780 24x200g 8x400g port configuration.
#
# configuration yaml file
#   device:
#       <unit>:
#           <table>:
#               ?
#                   <key_fld_1>: <value>
#                   <key_fld_2>: <value>
#                   ...
#                   <key_fld_n>: <value>
#               :
#                   <data_fld_1>: <value>
#                   <data_fld_2>: <value>
#                   ...
#                   <data_fld_n>: <value>
#

---
device:
    0:
        DEVICE_CONFIG:
            # CORE CLOCK FREQUENCY
            CORE_CLK_FREQ: CLK_1350MHZ
            # PP CLOCK FREQUENCY
            PP_CLK_FREQ: CLK_1350MHZ
...
---
device:
    0:  
        FP_CONFIG:
            FP_ING_OPERMODE: GLOBAL_PIPE_AWARE
...
---
bcm_device:
    0:  
        global:
            sai_remap_prio_on_tnl_egress: 1
            global_flexctr_ing_action_num_reserved: 32
            global_flexctr_ing_group_num_reserved: 2
            global_flexctr_ing_pool_num_reserved: 12
            global_flexctr_ing_quant_num_reserved: 2
            global_flexctr_ing_op_profile_num_reserved: 32
            l3_intf_vlan_split_egress: 1
            pktio_mode: 1
            bcm_tunnel_term_compatible_mode: 1
            vlan_flooding_l2mc_num_reserved: 0
            l3_alpm_template: 1
            l3_alpm2_bnk_threshold: 100 
            l2_hitbit_enable: 0
            uft_mode: 1
            l3_enable: 1
            ipv6_lpm_128b_enable: 1
            shared_block_mask_section: uc_bc
            skip_protocol_default_entries: 1
            sai_tunnel_support: 0
            flexctr_action_reserved_ipmc_hitbit: 1
            sai_nbr_bcast_ifp_optimized: 1
            use_all_splithorizon_groups: 1
            riot_enable: 1
            riot_overlay_l3_intf_mem_size: 8192
            riot_overlay_l3_egress_mem_size: 32768
            l3_ecmp_levels: 2
            riot_overlay_ecmp_resilient_hash_size: 16384
            sai_feat_tail_timestamp: 1
            sai_port_queue_ecn_counter: 1
            sai_field_group_auto_prioritize: 1
...
---
device:
    0:
        PC_PORT_PHYS_MAP:
            ?
                # CPU port
                PORT_ID: 0
            :
                PC_PHYS_PORT_ID: 0
            ?
                # pipe 0
                PORT_ID: 1
            :
                PC_PHYS_PORT_ID: 1
            ?
                PORT_ID: 2
            :
                PC_PHYS_PORT_ID: 5
            ?
                PORT_ID: 3
            :
                PC_PHYS_PORT_ID: 9
            ?
                PORT_ID: 4
            :
                PC_PHYS_PORT_ID: 13
            ?
                PORT_ID: 5
            :
                PC_PHYS_PORT_ID: 17
            ?
                PORT_ID: 6
            :
                PC_PHYS_PORT_ID: 21
            ?
                PORT_ID: 7
            :
                PC_PHYS_PORT_ID: 25
            ?
                PORT_ID: 8
            :
                PC_PHYS_PORT_ID: 29
            ?
                PORT_ID: 9
            :
                PC_PHYS_PORT_ID: 33
            ?
                PORT_ID: 10
            :
                PC_PHYS_PORT_ID: 37
            ?
                # pipe 1
                PORT_ID: 20
            :
                PC_PHYS_PORT_ID: 41
            ?
                PORT_ID: 21
            :
                PC_PHYS_PORT_ID: 45
            ?
                PORT_ID: 22
            :
                PC_PHYS_PORT_ID: 49
            ?
                PORT_ID: 23
            :
                PC_PHYS_PORT_ID: 53
            ?
                PORT_ID: 24
            :
                PC_PHYS_PORT_ID: 57
            ?
                PORT_ID: 25
            :
                PC_PHYS_PORT_ID: 61
            ?
                PORT_ID: 26
            :
                PC_PHYS_PORT_ID: 65
            ?
                PORT_ID: 27
            :
                PC_PHYS_PORT_ID: 69
            ?
                PORT_ID: 28
            :
                PC_PHYS_PORT_ID: 73
            ?
                PORT_ID: 29
            :
                PC_PHYS_PORT_ID: 77
            ?
                # pipe 2
                PORT_ID: 40
            :
                PC_PHYS_PORT_ID: 81
            ?
                PORT_ID: 41
            :
                PC_PHYS_PORT_ID: 85
            ?
                PORT_ID: 42
            :
                PC_PHYS_PORT_ID: 89
            ?
                PORT_ID: 43
            :
                PC_PHYS_PORT_ID: 93
            ?
                # BC12 400G
                PORT_ID: 44
            :
                PC_PHYS_PORT_ID: 97
            ?
                PORT_ID: 45
            :
                PC_PHYS_PORT_ID: 105
            ?
                PORT_ID: 46
            :
                PC_PHYS_PORT_ID: 113
            ?
                # pipe 3
                PORT_ID: 60
            :
                PC_PHYS_PORT_ID: 121
            ?
                PORT_ID: 61
            :
                PC_PHYS_PORT_ID: 129
            ?
                PORT_ID: 62
            :
                PC_PHYS_PORT_ID: 137
            ?
                PORT_ID: 63
            :
                PC_PHYS_PORT_ID: 145
            ?
                PORT_ID: 64
            :
                PC_PHYS_PORT_ID: 153
...
---
device:
    0:
        PC_PORT:
            ?
                PORT_ID: 0
            :
                &port_mode_10g
                ENABLE: 1
                SPEED: 10000
                NUM_LANES: 1
            ?
                PORT_ID: [[1, 10],
                          [20, 29],
                          [40, 43]]
            :
                &port_mode_200g
                ENABLE: 0
                SPEED: 200000
                NUM_LANES: 4
                FEC_MODE: PC_FEC_RS544_2XN
                LINK_TRAINING: 0
                MAX_FRAME_SIZE: 9416
            ?
                PORT_ID: [[44, 46],
                          [60, 64]]
            :
                &port_mode_400g
                ENABLE: 0
                SPEED: 400000
                NUM_LANES: 8
                FEC_MODE: PC_FEC_RS544_2XN
                LINK_TRAINING: 0
                MAX_FRAME_SIZE: 9416
...
---
device:
    0:
        # Per pipe flex counter configuration
        CTR_EFLEX_CONFIG:
            CTR_ING_EFLEX_OPERMODE_PIPEUNIQUE: 0
            CTR_EGR_EFLEX_OPERMODE_PIPEUNIQUE: 0
...
---
device:
    0:
        PC_PM_CORE:
            ?
                PC_PM_ID: 1
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x32105476
                TX_LANE_MAP: 0x54763210
                RX_POLARITY_FLIP: 0x0f
                TX_POLARITY_FLIP: 0xfa
            ?
                PC_PM_ID: 2
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x75043216
                TX_LANE_MAP: 0x32107456
                RX_POLARITY_FLIP: 0x53
                TX_POLARITY_FLIP: 0x5e
            ?
                PC_PM_ID: 3
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x54763210
                TX_LANE_MAP: 0x23104567
                RX_POLARITY_FLIP: 0x4c
                TX_POLARITY_FLIP: 0x03
            ?
                PC_PM_ID: 4
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x54763210
                TX_LANE_MAP: 0x23104756
                RX_POLARITY_FLIP: 0x14
                TX_POLARITY_FLIP: 0xa6
            ?
                PC_PM_ID: 5
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x54763210
                TX_LANE_MAP: 0x23104576
                RX_POLARITY_FLIP: 0x0c
                TX_POLARITY_FLIP: 0x80
            ?
                PC_PM_ID: 6
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x13206475
                TX_LANE_MAP: 0x46573210
                RX_POLARITY_FLIP: 0x00
                TX_POLARITY_FLIP: 0xc0
            ?
                PC_PM_ID: 7
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x13206475
                TX_LANE_MAP: 0x46573210
                RX_POLARITY_FLIP: 0x10
                TX_POLARITY_FLIP: 0xc0
            ?
                PC_PM_ID: 8
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x13206475
                TX_LANE_MAP: 0x46573210
                RX_POLARITY_FLIP: 0x00
                TX_POLARITY_FLIP: 0xc0
            ?
                PC_PM_ID: 9
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x05674123
                TX_LANE_MAP: 0x76543210
                RX_POLARITY_FLIP: 0xb5
                TX_POLARITY_FLIP: 0x0e
            ?
                PC_PM_ID: 10
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x45763210
                TX_LANE_MAP: 0x32105476
                RX_POLARITY_FLIP: 0x60
                TX_POLARITY_FLIP: 0x50
            ?
                PC_PM_ID: 11
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x32105476
                TX_LANE_MAP: 0x54763210
                RX_POLARITY_FLIP: 0x4f
                TX_POLARITY_FLIP: 0x2f
            ?
                PC_PM_ID: 12
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x41230567
                TX_LANE_MAP: 0x31207564
                RX_POLARITY_FLIP: 0xa
                TX_POLARITY_FLIP: 0x2a
            ?
                PC_PM_ID: 13
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x67243501
                TX_LANE_MAP: 0x53426170
                RX_POLARITY_FLIP: 0x3f
                TX_POLARITY_FLIP: 0xC3
            ?
                PC_PM_ID: 14
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x12743065
                TX_LANE_MAP: 0x42537061
                RX_POLARITY_FLIP: 0xd1
                TX_POLARITY_FLIP: 0x33
            ?
                PC_PM_ID: 15
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x74126530
                TX_LANE_MAP: 0x02136574
                RX_POLARITY_FLIP: 0x7e
                TX_POLARITY_FLIP: 0x33
            ?
                PC_PM_ID: 16
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x46352701
                TX_LANE_MAP: 0x27360514
                RX_POLARITY_FLIP: 0x36
                TX_POLARITY_FLIP: 0x61
            ?
                PC_PM_ID: 17
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x20534167
                TX_LANE_MAP: 0x34250617
                RX_POLARITY_FLIP: 0x7b
                TX_POLARITY_FLIP: 0xcc
            ?
                PC_PM_ID: 18
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x65034721
                TX_LANE_MAP: 0x24351607
                RX_POLARITY_FLIP: 0x74
                TX_POLARITY_FLIP: 0x63
            ?
                PC_PM_ID: 19
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x15473620
                TX_LANE_MAP: 0x57640213
                RX_POLARITY_FLIP: 0xf9
                TX_POLARITY_FLIP: 0x56
            ?
                PC_PM_ID: 20
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x23504167
                TX_LANE_MAP: 0x32056714
                RX_POLARITY_FLIP: 0x65
                TX_POLARITY_FLIP: 0x02
...


