#!/usr/bin/env python3

"""
auto-techsupport script.
    This script is invoked by the techsupport-monit.service & coredump-monit.service 
    for auto techsupport invocation and cleanup of techsupport & core dumps. 
    For more info, refer to the HLD
"""

import argparse
from swsscommon.swsscommon import SonicV2Connector

def main():
    parser = argparse.ArgumentParser(description='Auto Techsupport Invocation and Management Script')
    parser.add_argument('mode', type=str, choices=['core', 'techsupport'])
    args = parser.parse_args()
    
    if args.mode == "core":
        handle_core_dump_creation_event()
    else:
        handle_techsupport_creation_event()
    
def handle_core_dump_creation_event():
    pass

def handle_techsupport_creation_event():
    cfg_db = SonicV2Connector(host="127.0.0.1")
    cfg_db.connect("CONFIG_DB")
    
    state_db = SonicV2Connector(host="127.0.0.1")
    state_db.connect("STATE_DB")
    
    
    
    
    pass
    