# Bluefield2 Platform Modules

BF2_PLATFORM_MODULE_VERSION = 1.0

export BF2_PLATFORM_MODULE_VERSION

BF2_PLATFORM_MODULE = platform-modules-bf2_$(BF2_PLATFORM_MODULE_VERSION)_arm64.deb
$(BF2_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-bf2

# Bluefield Drivers
BF2_PLATFORM_DRIVERS = $(MLXBF_GIGE_DRIVER) $(IPMB_HOST_DRIVER) $(MLXBF_I2C_DRIVER)
BF2_PLATFORM_DRIVERS += $(MLX_TRIO_DRIVER) $(MLXBF_LIVEFISH_DRIVER) $(MLXBF_PMC_DRIVER)
BF2_PLATFORM_DRIVERS += $(TMFIFO_DRIVER) $(MLXBF2_GPIO_DRIVER) $(BLUEFIELD_EDAC_DRIVER)
BF2_PLATFORM_DRIVERS += $(MLX_BOOTCTL_DRIVER) $(IPMB_DEV_INT_DRIVER) $(MLXBF_PKA_DRIVER)

$(BF2_PLATFORM_MODULE)_FILES = $(BF2_PLATFORM_DRIVERS)
$(BF2_PLATFORM_MODULE)_PLATFORM = arm64-nvda_bf-mbf2m516a arm64-nvda_bf-mbf2h536c

SONIC_MAKE_DEBS += $(BF2_PLATFORM_MODULE)

export BF2_PLATFORM_MODULE
export BF2_PLATFORM_DRIVERS
