{% from "dockers/dockerfile-macros.j2" import install_debian_packages, install_python_wheels, copy_files %}
FROM docker-config-engine-bullseye-{{DOCKER_USERNAME}}:{{DOCKER_USERTAG}}

ARG docker_container_name
ARG image_version
RUN [ -f /etc/rsyslog.conf ] && sed -ri "s/%syslogtag%/$docker_container_name#%syslogtag%/;" /etc/rsyslog.conf

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

# Pass the image_version to container
ENV IMAGE_VERSION=$image_version

RUN apt-get update \
 && apt-get install -y \
      redis-server

{% if docker_gnmi_test_debs.strip() -%}
# Copy locally-built Debian package dependencies
{{ copy_files("debs/", docker_gnmi_test_debs.split(' '), "/debs/") }}

# Install locally-built Debian packages and implicitly install their dependencies
{{ install_debian_packages(docker_gnmi_test_debs.split(' ')) }}
{%- endif %}

RUN apt-get clean -y      && \
    apt-get autoclean -   && \
    apt-get autoremove -y && \
    rm -rf /debs

RUN mkdir -p /etc/sonic

# Adjust redis configurations
RUN sed -ri 's/^# unixsocket/unixsocket/' /etc/redis/redis.conf
RUN sed -ri 's/^unixsocketperm .../unixsocketperm 777/' /etc/redis/redis.conf
RUN sed -ri 's/redis-server.sock/redis.sock/' /etc/redis/redis.conf

COPY gnmi_cmd.sh /root/
COPY dash_example.sh /root/

COPY supervisor.conf /etc/supervisor/conf.d/
COPY gnmi.conf /etc/supervisor/conf.d/

COPY start.sh /usr/bin
RUN chmod +x /usr/bin/start.sh

COPY dsmsroot.key /root/
COPY dsmsroot.cer /root/
COPY gnmiserver.key /root/
COPY gnmiserver.cer /root/
COPY gnmiclient.key /root/
COPY gnmiclient.cer /root/

RUN cp /root/dsmsroot.cer /etc/sonic/
RUN cp /root/gnmiserver.cer /etc/sonic/
RUN cp /root/gnmiserver.key /etc/sonic/

ENTRYPOINT ["/usr/local/bin/supervisord"]
