ifcs:
  options:
    log_level: "error"
nodes:
- node_id: "0"
  options:
    sku: "configs/sku/teralynx.MVTX9180"
    netdev:
    - auto_create: "no"
      multi_interface: "yes"
    buffer_management_mode: "api_driven"
    pt01: "256"
    wred_cr_ip_proto_list: "17"
    cr_assignment_mode: "1"
    max_lossless_tc: "2"
    ilpm_enable: "1"
    forward_profile: "IFCS_FORWARD_PROFILE_ID_PROFILE_E"
    led_cfg_sck_rate: "0x5"
    led_refresh_precliff_timer: "0x18eec2"
    led_refresh_cliff_timer: "0x15e"
    led_cfg_pic_stream_mode: "1"
    led_refresh_tmr_ctl_enable: "1"
    skip_pll_check: "false"
    sys_clk: "1800"
    ifc_clk: "1800"
    mac_clk: "1600"
    txring:
    - txring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    rxring:
    - rxring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44"
    - rxring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "1, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45"
    - rxring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "2, 6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46"
    - rxring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "3, 7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47"
  devports:
  - id: "0"
    sysport: "1000"
    type: "cpu"
  - fec: "KPFEC"
    id: "489"
    lanes: "0:4"
    serdes_group: "61"
    speed: "100G"
    sysport: "489"
    type: "eth"
  - fec: "KPFEC"
    id: "505"
    lanes: "0:4"
    serdes_group: "63"
    speed: "100G"
    sysport: "505"
    type: "eth"
  - fec: "KPFEC"
    id: "441"
    lanes: "0:4"
    serdes_group: "55"
    speed: "100G"
    sysport: "441"
    type: "eth"
  - fec: "KPFEC"
    id: "425"
    lanes: "0:4"
    serdes_group: "53"
    speed: "100G"
    sysport: "425"
    type: "eth"
  - fec: "KPFEC"
    id: "41"
    lanes: "0:4"
    serdes_group: "5"
    speed: "100G"
    sysport: "41"
    type: "eth"
  - fec: "KPFEC"
    id: "49"
    lanes: "0:4"
    serdes_group: "6"
    speed: "100G"
    sysport: "49"
    type: "eth"
  - fec: "KPFEC"
    id: "153"
    lanes: "0:4"
    serdes_group: "19"
    speed: "100G"
    sysport: "153"
    type: "eth"
  - fec: "KPFEC"
    id: "137"
    lanes: "0:4"
    serdes_group: "17"
    speed: "100G"
    sysport: "137"
    type: "eth"
  - fec: "KPFEC"
    id: "1"
    lanes: "0:4"
    serdes_group: "0"
    speed: "100G"
    sysport: "1"
    type: "eth"
  - fec: "KPFEC"
    id: "17"
    lanes: "0:4"
    serdes_group: "2"
    speed: "100G"
    sysport: "17"
    type: "eth"
  - fec: "KPFEC"
    id: "81"
    lanes: "0:4"
    serdes_group: "10"
    speed: "100G"
    sysport: "81"
    type: "eth"
  - fec: "KPFEC"
    id: "65"
    lanes: "0:4"
    serdes_group: "8"
    speed: "100G"
    sysport: "65"
    type: "eth"
  - fec: "KPFEC"
    id: "97"
    lanes: "0:4"
    serdes_group: "12"
    speed: "100G"
    sysport: "97"
    type: "eth"
  - fec: "KPFEC"
    id: "113"
    lanes: "0:4"
    serdes_group: "14"
    speed: "100G"
    sysport: "113"
    type: "eth"
  - fec: "KPFEC"
    id: "193"
    lanes: "0:4"
    serdes_group: "24"
    speed: "100G"
    sysport: "193"
    type: "eth"
  - fec: "KPFEC"
    id: "177"
    lanes: "0:4"
    serdes_group: "22"
    speed: "100G"
    sysport: "177"
    type: "eth"
  - fec: "KPFEC"
    id: "33"
    lanes: "0:4"
    serdes_group: "4"
    speed: "100G"
    sysport: "33"
    type: "eth"
  - fec: "KPFEC"
    id: "57"
    lanes: "0:4"
    serdes_group: "7"
    speed: "100G"
    sysport: "57"
    type: "eth"
  - fec: "KPFEC"
    id: "161"
    lanes: "0:4"
    serdes_group: "20"
    speed: "100G"
    sysport: "161"
    type: "eth"
  - fec: "KPFEC"
    id: "129"
    lanes: "0:4"
    serdes_group: "16"
    speed: "100G"
    sysport: "129"
    type: "eth"
  - fec: "KPFEC"
    id: "217"
    lanes: "0:4"
    serdes_group: "27"
    speed: "100G"
    sysport: "217"
    type: "eth"
  - fec: "KPFEC"
    id: "241"
    lanes: "0:4"
    serdes_group: "30"
    speed: "100G"
    sysport: "241"
    type: "eth"
  - fec: "KPFEC"
    id: "233"
    lanes: "0:4"
    serdes_group: "29"
    speed: "100G"
    sysport: "233"
    type: "eth"
  - fec: "KPFEC"
    id: "209"
    lanes: "0:4"
    serdes_group: "26"
    speed: "100G"
    sysport: "209"
    type: "eth"
  - fec: "KPFEC"
    id: "105"
    lanes: "0:4"
    serdes_group: "13"
    speed: "100G"
    sysport: "105"
    type: "eth"
  - fec: "KPFEC"
    id: "121"
    lanes: "0:4"
    serdes_group: "15"
    speed: "100G"
    sysport: "121"
    type: "eth"
  - fec: "KPFEC"
    id: "169"
    lanes: "0:4"
    serdes_group: "21"
    speed: "100G"
    sysport: "169"
    type: "eth"
  - fec: "KPFEC"
    id: "145"
    lanes: "0:4"
    serdes_group: "18"
    speed: "100G"
    sysport: "145"
    type: "eth"
  - fec: "KPFEC"
    id: "265"
    lanes: "0:4"
    serdes_group: "33"
    speed: "100G"
    sysport: "265"
    type: "eth"
  - fec: "KPFEC"
    id: "289"
    lanes: "0:4"
    serdes_group: "36"
    speed: "100G"
    sysport: "289"
    type: "eth"
  - fec: "KPFEC"
    id: "297"
    lanes: "0:4"
    serdes_group: "37"
    speed: "100G"
    sysport: "297"
    type: "eth"
  - fec: "KPFEC"
    id: "273"
    lanes: "0:4"
    serdes_group: "34"
    speed: "100G"
    sysport: "273"
    type: "eth"
  - fec: "KPFEC"
    id: "225"
    lanes: "0:4"
    serdes_group: "28"
    speed: "100G"
    sysport: "225"
    type: "eth"
  - fec: "KPFEC"
    id: "249"
    lanes: "0:4"
    serdes_group: "31"
    speed: "100G"
    sysport: "249"
    type: "eth"
  - fec: "KPFEC"
    id: "201"
    lanes: "0:4"
    serdes_group: "25"
    speed: "100G"
    sysport: "201"
    type: "eth"
  - fec: "KPFEC"
    id: "185"
    lanes: "0:4"
    serdes_group: "23"
    speed: "100G"
    sysport: "185"
    type: "eth"
  - fec: "KPFEC"
    id: "393"
    lanes: "0:4"
    serdes_group: "49"
    speed: "100G"
    sysport: "393"
    type: "eth"
  - fec: "KPFEC"
    id: "409"
    lanes: "0:4"
    serdes_group: "51"
    speed: "100G"
    sysport: "409"
    type: "eth"
  - fec: "KPFEC"
    id: "329"
    lanes: "0:4"
    serdes_group: "41"
    speed: "100G"
    sysport: "329"
    type: "eth"
  - fec: "KPFEC"
    id: "313"
    lanes: "0:4"
    serdes_group: "39"
    speed: "100G"
    sysport: "313"
    type: "eth"
  - fec: "KPFEC"
    id: "257"
    lanes: "0:4"
    serdes_group: "32"
    speed: "100G"
    sysport: "257"
    type: "eth"
  - fec: "KPFEC"
    id: "281"
    lanes: "0:4"
    serdes_group: "35"
    speed: "100G"
    sysport: "281"
    type: "eth"
  - fec: "KPFEC"
    id: "321"
    lanes: "0:4"
    serdes_group: "40"
    speed: "100G"
    sysport: "321"
    type: "eth"
  - fec: "KPFEC"
    id: "305"
    lanes: "0:4"
    serdes_group: "38"
    speed: "100G"
    sysport: "305"
    type: "eth"
  - fec: "KPFEC"
    id: "457"
    lanes: "0:4"
    serdes_group: "57"
    speed: "100G"
    sysport: "457"
    type: "eth"
  - fec: "KPFEC"
    id: "465"
    lanes: "0:4"
    serdes_group: "58"
    speed: "100G"
    sysport: "465"
    type: "eth"
  - fec: "KPFEC"
    id: "369"
    lanes: "0:4"
    serdes_group: "46"
    speed: "100G"
    sysport: "369"
    type: "eth"
  - fec: "KPFEC"
    id: "353"
    lanes: "0:4"
    serdes_group: "44"
    speed: "100G"
    sysport: "353"
    type: "eth"
  - fec: "KPFEC"
    id: "385"
    lanes: "0:4"
    serdes_group: "48"
    speed: "100G"
    sysport: "385"
    type: "eth"
  - fec: "KPFEC"
    id: "401"
    lanes: "0:4"
    serdes_group: "50"
    speed: "100G"
    sysport: "401"
    type: "eth"
  - fec: "KPFEC"
    id: "361"
    lanes: "0:4"
    serdes_group: "45"
    speed: "100G"
    sysport: "361"
    type: "eth"
  - fec: "KPFEC"
    id: "337"
    lanes: "0:4"
    serdes_group: "42"
    speed: "100G"
    sysport: "337"
    type: "eth"
  - fec: "KPFEC"
    id: "481"
    lanes: "0:4"
    serdes_group: "60"
    speed: "100G"
    sysport: "481"
    type: "eth"
  - fec: "KPFEC"
    id: "497"
    lanes: "0:4"
    serdes_group: "62"
    speed: "100G"
    sysport: "497"
    type: "eth"
  - fec: "KPFEC"
    id: "433"
    lanes: "0:4"
    serdes_group: "54"
    speed: "100G"
    sysport: "433"
    type: "eth"
  - fec: "KPFEC"
    id: "417"
    lanes: "0:4"
    serdes_group: "52"
    speed: "100G"
    sysport: "417"
    type: "eth"
  - fec: "KPFEC"
    id: "449"
    lanes: "0:4"
    serdes_group: "56"
    speed: "100G"
    sysport: "449"
    type: "eth"
  - fec: "KPFEC"
    id: "473"
    lanes: "0:4"
    serdes_group: "59"
    speed: "100G"
    sysport: "473"
    type: "eth"
  - fec: "KPFEC"
    id: "377"
    lanes: "0:4"
    serdes_group: "47"
    speed: "100G"
    sysport: "377"
    type: "eth"
  - fec: "KPFEC"
    id: "345"
    lanes: "0:4"
    serdes_group: "43"
    speed: "100G"
    sysport: "345"
    type: "eth"
  - fec: "KPFEC"
    id: "9"
    lanes: "0:4"
    serdes_group: "1"
    speed: "100G"
    sysport: "9"
    type: "eth"
  - fec: "KPFEC"
    id: "25"
    lanes: "0:4"
    serdes_group: "3"
    speed: "100G"
    sysport: "25"
    type: "eth"
  - fec: "KPFEC"
    id: "89"
    lanes: "0:4"
    serdes_group: "11"
    speed: "100G"
    sysport: "89"
    type: "eth"
  - fec: "KPFEC"
    id: "73"
    lanes: "0:4"
    serdes_group: "9"
    speed: "100G"
    sysport: "73"
    type: "eth"
  isg:
  - id: "0"
    lane_swap: "74563102"
    rx_polarity: "11000001"
    tx_polarity: "00011100"
  - id: "1"
    lane_swap: "74563102"
    rx_polarity: "01110111"
    tx_polarity: "01111100"
  - id: "2"
    lane_swap: "20136547"
    rx_polarity: "10001110"
    tx_polarity: "01110011"
  - id: "3"
    lane_swap: "20136547"
    rx_polarity: "10001100"
    tx_polarity: "00101011"
  - id: "4"
    lane_swap: "74563102"
    rx_polarity: "11000001"
    tx_polarity: "00011100"
  - id: "5"
    lane_swap: "47563102"
    rx_polarity: "00010111"
    tx_polarity: "00111101"
  - id: "6"
    lane_swap: "02134567"
    rx_polarity: "00101110"
    tx_polarity: "01000000"
  - id: "7"
    lane_swap: "02134567"
    rx_polarity: "00101110"
    tx_polarity: "10010010"
  - id: "8"
    lane_swap: "67451302"
    rx_polarity: "10100010"
    tx_polarity: "10011110"
  - id: "9"
    lane_swap: "67453102"
    rx_polarity: "10100010"
    tx_polarity: "10111010"
  - id: "10"
    lane_swap: "20315476"
    rx_polarity: "01101101"
    tx_polarity: "10010001"
  - id: "11"
    lane_swap: "20315476"
    rx_polarity: "10111111"
    tx_polarity: "11010001"
  - id: "12"
    lane_swap: "76543120"
    rx_polarity: "10100101"
    tx_polarity: "11101000"
  - id: "13"
    lane_swap: "76543120"
    rx_polarity: "10011110"
    tx_polarity: "10100010"
  - id: "14"
    lane_swap: "02134567"
    rx_polarity: "10011110"
    tx_polarity: "11110101"
  - id: "15"
    lane_swap: "02134567"
    rx_polarity: "11010001"
    tx_polarity: "01101101"
  - id: "16"
    lane_swap: "67451302"
    rx_polarity: "00101010"
    tx_polarity: "01100011"
  - id: "17"
    lane_swap: "54760132"
    rx_polarity: "01010100"
    tx_polarity: "10010101"
  - id: "18"
    lane_swap: "54761032"
    rx_polarity: "10101011"
    tx_polarity: "01011000"
  - id: "19"
    lane_swap: "23016745"
    rx_polarity: "00100000"
    tx_polarity: "11111000"
  - id: "20"
    lane_swap: "20315476"
    rx_polarity: "10000101"
    tx_polarity: "11011111"
  - id: "21"
    lane_swap: "23016745"
    rx_polarity: "11110100"
    tx_polarity: "00010111"
  - id: "22"
    lane_swap: "54760132"
    rx_polarity: "10001011"
    tx_polarity: "11010101"
  - id: "23"
    lane_swap: "54761032"
    rx_polarity: "11110100"
    tx_polarity: "01011000"
  - id: "24"
    lane_swap: "23016745"
    rx_polarity: "01110000"
    tx_polarity: "10111000"
  - id: "25"
    lane_swap: "23016745"
    rx_polarity: "10111011"
    tx_polarity: "00000111"
  - id: "26"
    lane_swap: "02134567"
    rx_polarity: "00010101"
    tx_polarity: "11001001"
  - id: "27"
    lane_swap: "20314576"
    rx_polarity: "11010110"
    tx_polarity: "10110001"
  - id: "28"
    lane_swap: "20314576"
    rx_polarity: "11110011"
    tx_polarity: "10110001"
  - id: "29"
    lane_swap: "76453120"
    rx_polarity: "01101101"
    tx_polarity: "01001000"
  - id: "30"
    lane_swap: "67541302"
    rx_polarity: "00110111"
    tx_polarity: "11110101"
  - id: "31"
    lane_swap: "67541302"
    rx_polarity: "01100111"
    tx_polarity: "01000111"
  - id: "32"
    lane_swap: "67543120"
    rx_polarity: "00011110"
    tx_polarity: "11111000"
  - id: "33"
    lane_swap: "67543120"
    rx_polarity: "10011010"
    tx_polarity: "10011000"
  - id: "34"
    lane_swap: "67453102"
    rx_polarity: "11011001"
    tx_polarity: "10100001"
  - id: "35"
    lane_swap: "02134576"
    rx_polarity: "01010101"
    tx_polarity: "00110111"
  - id: "36"
    lane_swap: "02134576"
    rx_polarity: "10100001"
    tx_polarity: "11100110"
  - id: "37"
    lane_swap: "20315476"
    rx_polarity: "11000100"
    tx_polarity: "10001010"
  - id: "38"
    lane_swap: "23016745"
    rx_polarity: "01100101"
    tx_polarity: "11101111"
  - id: "39"
    lane_swap: "23017645"
    rx_polarity: "10000101"
    tx_polarity: "11111110"
  - id: "40"
    lane_swap: "54761032"
    rx_polarity: "11011111"
    tx_polarity: "00001101"
  - id: "41"
    lane_swap: "54761032"
    rx_polarity: "00100100"
    tx_polarity: "01001000"
  - id: "42"
    lane_swap: "23016745"
    rx_polarity: "11010101"
    tx_polarity: "01000000"
  - id: "43"
    lane_swap: "20315476"
    rx_polarity: "10101101"
    tx_polarity: "00010001"
  - id: "44"
    lane_swap: "23017645"
    rx_polarity: "11010101"
    tx_polarity: "11101011"
  - id: "45"
    lane_swap: "54761032"
    rx_polarity: "00101111"
    tx_polarity: "10110010"
  - id: "46"
    lane_swap: "54761032"
    rx_polarity: "11111011"
    tx_polarity: "01011101"
  - id: "47"
    lane_swap: "67451302"
    rx_polarity: "00111000"
    tx_polarity: "00010110"
  - id: "48"
    lane_swap: "02134567"
    rx_polarity: "00011111"
    tx_polarity: "01000101"
  - id: "49"
    lane_swap: "02134567"
    rx_polarity: "00011110"
    tx_polarity: "00001111"
  - id: "50"
    lane_swap: "76543120"
    rx_polarity: "11101011"
    tx_polarity: "10110000"
  - id: "51"
    lane_swap: "76543120"
    rx_polarity: "10100100"
    tx_polarity: "11010111"
  - id: "52"
    lane_swap: "20314576"
    rx_polarity: "01000101"
    tx_polarity: "01011101"
  - id: "53"
    lane_swap: "20315476"
    rx_polarity: "01000101"
    tx_polarity: "01011111"
  - id: "54"
    lane_swap: "67451302"
    rx_polarity: "10011101"
    tx_polarity: "11101011"
  - id: "55"
    lane_swap: "67451302"
    rx_polarity: "10110000"
    tx_polarity: "11101011"
  - id: "56"
    lane_swap: "02134567"
    rx_polarity: "11100000"
    tx_polarity: "10111010"
  - id: "57"
    lane_swap: "02134567"
    rx_polarity: "10101110"
    tx_polarity: "10111010"
  - id: "58"
    lane_swap: "47651320"
    rx_polarity: "00110110"
    tx_polarity: "10101000"
  - id: "59"
    lane_swap: "47651320"
    rx_polarity: "00110110"
    tx_polarity: "10101100"
  - id: "60"
    lane_swap: "02315674"
    rx_polarity: "11010101"
    tx_polarity: "01111110"
  - id: "61"
    lane_swap: "02315674"
    rx_polarity: "11000100"
    tx_polarity: "01011110"
  - id: "62"
    lane_swap: "47651320"
    rx_polarity: "10010000"
    tx_polarity: "11101110"
  - id: "63"
    lane_swap: "47651320"
    rx_polarity: "10010110"
    tx_polarity: "10100100"
