#!/bin/bash
#
# Copyright (c) 2021 NVIDIA CORPORATION & AFFILIATES.
# Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This script generates the corresponding SONiC installer images for Bluefield
# 1) BFB Image
# 2) PXE Archive for Network Booting
# 3) BIN Image for SONiC-SONiC Installation

set -e

WDIR=
IMAGE_VERSION=
KERNEL_VERSION=
CHROOT_DIR=
INITRD=
VMLINUZ=
MODULES_DIR=

CDIR=/sonic/
SDIR=$CDIR/installer/bluefield
DDIR=$CDIR
CAPSULE=/lib/firmware/mellanox/boot/capsule/boot_update2.cap
BOOTCTL_DRIVER=$CDIR/$FILES_PATH/mlx-bootctl.ko
TMFIFO_DRIVER=$CDIR/$FILES_PATH/mlxbf-tmfifo.ko
SDHCI_OF_DWCMSHC_DRIVER=$CDIR/$FILES_PATH/sdhci-of-dwcmshc.ko
TARGET_MACHINE=nvidia-bluefield
BFB="${BFB:-/lib/firmware/mellanox/boot/default.bfb}"
GRUB_AA64=grubnetaa64.efi
GRUB_CFG="" # Common Grub Config
BF2_BOOT_ARGS="console=ttyAMA1 console=hvc0 console=ttyAMA0 earlycon=pl011,0x01000000 earlycon=pl011,0x01800000"
BF2_GRUB_CFG="$BF2_BOOT_ARGS isolcpus=1-7 nohz_full=1-7 rcu_nocbs=1-7"
BF3_BOOT_ARGS="console=ttyAMA1 console=hvc0 console=ttyAMA0 earlycon=pl011,0x13010000"
BF3_GRUB_CFG="$BF3_BOOT_ARGS isolcpus=1-13 nohz_full=1-13 rcu_nocbs=1-13"

usage() {
cat << EOF
Usage: `basename $0` [ OPTIONS ]
OPTIONS:
-k, --kernel <kernel version>     Kernel version for the SmartNIC.
-v, --verbose                     Run script in verbose mode. Will print out each step of execution.
-h, --help                        Display help
EOF
}

parse_args() {
    while [[ $@ != "" ]]; do
        case $1 in
            -h|--help)
                usage
                exit 0
                ;;
            -v|--verbose)
                shift
                set -x
                ;;
            -k|--kernel)
                shift
                KERNEL_VERSION=$1
                ;;
            *)
                usage
                exit 1
                ;;
        esac
        shift
    done
}

clean_dir()
{
    rm -rf $1
    exit $2
}

generate_s2s_installer_image_bluefield()
{
    if  [ ! -d /sonic/installer ] || [ ! -r /sonic/installer/sharch_body.sh ] ; then
        echo "Error: Invalid installer script directory: installer"
        exit 1
    fi

    if  [ ! -d /sonic/installer/bluefield ] || [ ! -r /sonic/installer/bluefield/sonic_to_sonic.sh.j2 ] ; then
        echo "Error: Invalid arch installer directory: installer/bluefield"
        exit 1
    fi

    # Copy platform-specific installer config files
    rm -rf /sonic/installer/bluefield/platforms/
    mkdir -p /sonic/installer/bluefield/platforms/
    for PLATFORM in `ls ./device/nvidia-bluefield`; do
        if [ -f /sonic/device/nvidia-bluefield/$PLATFORM/installer.conf ]; then
            cp /sonic/device/nvidia-bluefield/$PLATFORM/installer.conf /sonic/installer/bluefield/platforms/$PLATFORM
        fi
    done

    echo -n "Building self-extracting installer image ."
    tmp_dir=$(mktemp --directory)
    tmp_installdir="$tmp_dir/installer"
    mkdir $tmp_installdir || clean_dir $tmp_dir 1

    # Replace the build time flags inside the sonic_to_sonic.sh script
    j2 /sonic/installer/bluefield/sonic_to_sonic.sh.j2 -o $tmp_installdir/install.sh || clean_dir $tmp_dir 1
    chmod 0755 $tmp_installdir/install.sh

    # Copy the payload file
    cp $ONIE_INSTALLER_PAYLOAD $tmp_installdir || clean_dir $tmp_dir 1

    # Create machine.conf file
    echo "machine=nvidia-bluefield" > $tmp_installdir/machine.conf
    echo "platform=arm64" >> $tmp_installdir/machine.conf

    sharch="$tmp_dir/sharch.tar"
    tar -C $tmp_dir -cf $sharch installer || {
        echo "Error: Problems creating $sharch archive"
        clean_dir $tmp_dir 1
    }

    [ -f "$sharch" ] || {
        echo "Error: $sharch not found"
        clean_dir $tmp_dir 1
    }

    sha1=$(cat $sharch | sha1sum | awk '{print $1}')
    echo -n "."

    cp /sonic/installer/sharch_body.sh /sonic/$OUTPUT_ONIE_IMAGE || {
        echo "Error: Problems copying sharch_body.sh"
        clean_dir 1
    }

    # Replace variables in the sharch template
    sed -i -e "s/%%IMAGE_SHA1%%/$sha1/" /sonic/$OUTPUT_ONIE_IMAGE
    echo -n "."
    tar_size="$(wc -c < "${sharch}")"
    sed -i -e "s|%%PAYLOAD_IMAGE_SIZE%%|${tar_size}|" /sonic/$OUTPUT_ONIE_IMAGE
    cat $sharch >> /sonic/$OUTPUT_ONIE_IMAGE
    rm -rf $tmp_dir

    echo " Done."
    echo "Success: sonic-sonic installer install image for bluefield is ready in /sonic/${OUTPUT_ONIE_IMAGE}:"

    clean_dir $tmp_dir  0
}

validate_config() {
    if [[ ! -f "$INITRD" ]]; then
        echo "[create_sonic_image] Error! SONiC INITRD not found"
        exit 1
    fi

    if [[ ! -f "$VMLINUZ" ]]; then
        echo "[create_sonic_image] Error! SONiC VMLINUZ not found"
        exit 1
    fi

    if [[ ! -d "$MODULES_DIR" ]]; then
        echo "[create_sonic_image] Error! Path to Kernel Modules not found"
        exit 1
    fi

    if [[ ! -n "$OUTPUT_BFB_IMAGE" ]]; then
        echo "[create_sonic_image] Error! OUTPUT_BFB_IMAGE name not defined. Exiting.."
        exit 1
    fi

    if [[ ! -f "$CDIR/$ONIE_INSTALLER_PAYLOAD" ]]; then
        echo "$ONIE_INSTALLER_PAYLOAD not found. Exiting.."
        exit 1
    fi

    mkbfb=`which mlx-mkbfb`
    if [[ ! -x "${mkbfb}" ]]; then
        echo "Error! mlx-mkbfb is required to build BFB image"
        exit 1
    fi

    if [[ ! -f $CAPSULE ]]; then
        echo "ERROR: Capsule file $CAPSULE does not exist"
        exit 1
    fi

    if [[ ! -f $BOOTCTL_DRIVER ]]; then
        echo "ERROR: Bootctl driver $BOOTCTL_DRIVER does not exist"
        exit 1
    fi

    if [[ ! -f $TMFIFO_DRIVER ]]; then
        echo "ERROR: Bootctl driver $TMFIFO_DRIVER does not exist"
        exit 1
    fi

    if [[ ! -f $SDHCI_OF_DWCMSHC_DRIVER ]]; then
        echo "ERROR: Bootctl driver $SDHCI_OF_DWCMSHC_DRIVER does not exist"
        exit 1
    fi

    if [[ ! -f $BFB ]]; then
        echo "ERROR: Default BFB $BFB does not exist"
        exit 1
    fi
}

cleanup_workdir() {
    rm -rf $boot_args $boot_args2 $boot_path $boot_desc $arxiv_wdir $WDIR
}

create_workdir() {
    if [[ $WDIR == "" ]]; then
        WDIR=$(mktemp -d /sonic/bfb-wd-XXXX)
    else
        rm -rf $WDIR/*
    fi
    boot_args=$(mktemp /tmp/boot-args-XXXX)
    boot_args2=$(mktemp /tmp/boot-args2-XXXX)
    boot_path=$(mktemp /tmp/boot-path-XXXX)
    boot_desc=$(mktemp /tmp/boot-desc-XXXX)
    arxiv_wdir=$(mktemp -d /tmp/pxe-wd-XXXX)
    trap cleanup_workdir EXIT
}

add_sonic_to_initramfs() {
    # Add the logic to put second stage installer into bfb initramfs
    mkdir -p debian

    j2 ${SDIR}/install.sh.j2 -o ./debian/install.sh
    chmod 0755 ./debian/install.sh

    # Copy the INSTALLER payload
    cp $CDIR/$ONIE_INSTALLER_PAYLOAD ./debian/

cat > scripts/initrd-install << EOF
#!/bin/bash

printf_msg()
{
	echo "$@" | tee /dev/kmsg
	return 0
}

depmod -a $KERNEL_VERSION > /dev/null 2>&1
insmod /mlx-bootctl.ko
insmod /sdhci-of-dwcmshc.ko
insmod /sbsa_gwdt.ko
/usr/sbin/watchdog

printf_msg "================================="
printf_msg "Installing SONiC. Please wait..."
printf_msg "================================="

/bin/bash /debian/install.sh
if [ \$? -eq 0 ]; then
	printf_msg "==================================="
	printf_msg "Installation finished. Rebooting..."
	printf_msg "==================================="
	printf_msg
	reboot -f
else
	printf_msg "========================"
	printf_msg "Failed to install SONiC"
	printf_msg "========================"
fi
EOF
    chmod +x scripts/initrd-install
    sudo rm -f conf/conf.d/debian-core*
    sudo sh -c 'echo "BOOT=initrd-install" > conf/conf.d/initrd_install'
    sudo sh -c 'echo "ROOT=\"LABEL=writable\"" > conf/conf.d/default_root'
}

copy_bin()
{
    if [ -e $1 ]; then
        bin=$1
    else
        bin=`which $1 2> /dev/null`
    fi

    if [[ -z "$bin" ]]; then
        echo "ERROR: Cannot find $1"
        exit 1
    else
        sudo mkdir -p .`dirname $bin`
        if [ ! -e .${bin} ]; then
            sudo cp -a $bin .${bin}
        fi

        # Copy dependencies
        for lib in `ldd $bin 2> /dev/null | grep '=>' | awk '{print $3}'`
        do
            if [ -e .$lib ]; then
                continue
            fi
            sudo mkdir -p .`dirname $lib`
            sudo cp -a $lib .$lib
            if [ -h $lib ]; then
                tlib=`readlink -f $lib`
                if [ ! -e .$tlib ]; then
                    sudo mkdir -p .`dirname $tlib`
                    sudo cp $tlib .$tlib
                fi
            fi
	    done
	fi
}

create_bfb_image() {

    pushd $WDIR

    # Copy the initrd into the work directory
    initramfs=$(realpath $INITRD)
    cp $initramfs $WDIR/dump-initramfs-v0
    initramfs=$WDIR/dump-initramfs-v0

    case "$(file --brief --mime-type "$initramfs")" in
        "application/x-lzma")
            cat_initrd="lzcat" ;;
        "application/x-lz4")
            cat_initrd="lz4cat" ;;
        *)
            cat_initrd="zcat" ;;
    esac

    echo "Rebuilding $initramfs"

    mkdir -p ${WDIR}/initramfs
    pushd initramfs
    $cat_initrd "$initramfs" | cpio -i

    # Remove tools coming with busybox
    for tool in `dpkg -L mlxbf-scripts | grep bin/` \
            `dpkg -L grub2-common` \
            `dpkg -L dosfstools` \
            `dpkg -L e2fsprogs` \
            `dpkg -L fdisk` \
            `dpkg -L kmod | grep -v share` \
            `dpkg -L pciutils | grep -v share` \
            `dpkg -L usbutils | grep -v share` \
            `dpkg -L mft` \
            `dpkg -L mft-oem` \
            `dpkg -L kernel-mft-modules` \
            `dpkg -L tar` \
            /usr/sbin/watchdog
    do
        if [ -d $tool ]; then
            continue
        fi
        /bin/rm -f .${tool}
    done

    for tool in `dpkg -L mlxbf-scripts | grep bin/` \
            `dpkg -L dosfstools | grep -v share` \
            `dpkg -L e2fsprogs | grep -v share` \
            `dpkg -L grub2-common` \
            `dpkg -L fdisk | grep -v share` \
            `dpkg -L kmod | grep -v share` \
            `dpkg -L pciutils | grep -v share` \
            `dpkg -L usbutils | grep -v share` \
            `dpkg -L mft` \
            `dpkg -L mft-oem` \
            `dpkg -L kernel-mft-modules` \
            `dpkg -L tar | grep -v share` \
            `dpkg -L grub-efi-arm64-bin` \
            xz efibootmgr gcc-10 bash getopt hexdump lspci perl \
            lsblk shutdown systemctl strings aarch64-linux-gnu-strings \
            mlxbf-bootctl id mkfs fsck watchdog
    do
        if [ -d $tool ]; then
            continue
        fi
        copy_bin $tool
    done

    sudo depmod -a -b ./ $KERNEL_VERSION
    mkdir -p usr/share/misc/ bin/ var/log/watchdog
    sudo cp /etc/watchdog.conf etc
    sudo cp /usr/share/misc/pci.ids usr/share/misc/
    cp $CHROOT_DIR/usr/share/misc/pci.ids usr/share/misc/
    cp $BOOTCTL_DRIVER .
    cp $TMFIFO_DRIVER .
    cp $SDHCI_OF_DWCMSHC_DRIVER .
    cp $WATCHDOG .

    mkdir -p ./lib/firmware/mellanox/boot/
    cp /lib/firmware/mellanox/boot/default.bfb ./lib/firmware/mellanox/boot/default.bfb
    cp -a /lib/firmware/mellanox/boot/capsule ./lib/firmware/mellanox/boot/
    mkdir -p mnt dev sys proc

    add_sonic_to_initramfs

    # Make initramfs with new debian
    find . -print0 | sudo cpio --null -o --format=newc | gzip -9 > "$initramfs"

    popd

    printf "$BF2_BOOT_ARGS initrd=initramfs" > \
        "$boot_args"
    printf "$BF3_BOOT_ARGS initrd=initramfs" > \
        "$boot_args2"

    printf "VenHw(F019E406-8C9C-11E5-8797-001ACA00BFC4)/Image" > "$boot_path"
    printf "Linux from rshim" > "$boot_desc"
    vmlinuz=$WDIR/vmlinuz
    cat $VMLINUZ > "$vmlinuz"

    $mkbfb --image "$vmlinuz" \
           --initramfs "$initramfs" \
           --capsule "$CAPSULE" \
           --boot-args-v0 "$boot_args" \
           --boot-args-v2 "$boot_args2" \
           --boot-path "$boot_path" \
           --boot-desc "$boot_desc" \
            ${BFB} ${DDIR}/${OUTPUT_BFB_IMAGE}

    echo "BFB is ready: $(readlink -f  ${DDIR}/${OUTPUT_BFB_IMAGE})"

    popd
}

create_pxe_archive(){
    # Installed by grub-efi-arm64-bin deb package
    if [[ ! -f "/usr/lib/grub/arm64-efi/monolithic/$GRUB_AA64" ]]; then
        echo "Grub EFI binary not found, check if grub-efi-arm64-bin package is installed"
        exit 1
    fi

    pushd $arxiv_wdir

    cp /usr/lib/grub/arm64-efi/monolithic/$GRUB_AA64 .

    cp $WDIR/vmlinuz Image
    cp $WDIR/dump-initramfs-v0 initramfs

    console_params=$BF2_BOOT_ARGS j2 /sonic/installer/bluefield/grub.cfg.j2 > bluefield-2.grub.cfg
    console_params=$BF3_BOOT_ARGS j2 /sonic/installer/bluefield/grub.cfg.j2 > bluefield-3.grub.cfg
    cp /sonic/installer/bluefield/PXE_README.txt .

    tar -C $arxiv_wdir -cvzf ${DDIR}/${OUTPUT_PXE_IMAGE} .

    popd
}

main() {
    echo $@
    parse_args $@

    . $CDIR/onie-image-arm64.conf

    # Export ENV Variables for j2cli
    CHROOT_DIR=$CDIR/$FILESYSTEM_ROOT
    if [[ ! -d "$CHROOT_DIR" ]]; then
        echo "[create_sonic_image] Error! Path to CHROOT not found"
        exit 1
    fi

    export GRUB_CFG=$(cat /sonic/installer/bluefield/sonic-grub.cfg)
    export IMAGE_VERSION=$(cat $CHROOT_DIR/etc/sonic/sonic_version.yml | grep "build_version" | sed -e "s/build_version: //g;s/'//g")
    export BF2_BOOT_ARGS BF3_BOOT_ARGS BF2_GRUB_CFG BF3_GRUB_CFG ONIE_INSTALLER_PAYLOAD FILESYSTEM_DOCKERFS DOCKERFS_DIR FILESYSTEM_SQUASHFS KERNEL_VERSION

    if [[ $IMAGE_TYPE == bin ]]; then
        # bluefield Doesn't have ONiE Support yet and this *.bin image generated can only be used for SONiC-SONiC installation
        echo "Build SONiC to SONiC installer for Bluefield"
        mkdir -p `dirname $OUTPUT_ONIE_IMAGE`
        sudo rm -f $OUTPUT_ONIE_IMAGE
        generate_s2s_installer_image_bluefield
    else
        INITRD=$CDIR/$FILESYSTEM_ROOT/boot/initrd.img-$KERNEL_VERSION
        VMLINUZ=$CDIR/$FILESYSTEM_ROOT/boot/vmlinuz-$KERNEL_VERSION
        MODULES_DIR=$CDIR/$FILESYSTEM_ROOT/lib/modules/$KERNEL_VERSION
        WATCHDOG=$MODULES_DIR/kernel/drivers/watchdog/sbsa_gwdt.ko

        validate_config

        create_workdir
        echo "Work directory: $WDIR"

        create_bfb_image

        if [[ $IMAGE_TYPE == pxe ]]; then
            create_pxe_archive
        fi
    fi
}

main $@
