# trixie-based docker image for sonic swss layer

DOCKER_SWSS_LAYER_TRIXIE = docker-swss-layer-trixie.gz
$(DOCKER_SWSS_LAYER_TRIXIE)_PATH = $(DOCKERS_PATH)/docker-swss-layer-trixie

$(DOCKER_SWSS_LAYER_TRIXIE)_DEPENDS += $(SWSS)
$(DOCKER_SWSS_LAYER_TRIXIE)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_TRIXIE)

$(DOCKER_SWSS_LAYER_TRIXIE)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_TRIXIE)_DBG_DEPENDS) \
                                             $(SWSS_DBG)
$(DOCKER_SWSS_LAYER_TRIXIE)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_TRIXIE)_DBG_IMAGE_PACKAGES)

SONIC_DOCKER_IMAGES += $(DOCKER_SWSS_LAYER_TRIXIE)
SONIC_TRIXIE_DOCKERS += $(DOCKER_SWSS_LAYER_TRIXIE)
