# docker image for gnmi test container

DOCKER_GNMI_TEST_STEM = docker-gnmi-test
DOCKER_GNMI_TEST = $(DOCKER_GNMI_TEST_STEM).gz
DOCKER_GNMI_TEST_DBG = $(DOCKER_GNMI_TEST_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_GNMI_TEST)_PATH = $(DOCKERS_PATH)/$(DOCKER_GNMI_TEST_STEM)

$(DOCKER_GNMI_TEST)_DEPENDS += $(SONIC_MGMT_COMMON)
$(DOCKER_GNMI_TEST)_DEPENDS += $(SONIC_TELEMETRY)
$(DOCKER_GNMI_TEST)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_BULLSEYE)_DBG_DEPENDS)

$(DOCKER_GNMI_TEST)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BULLSEYE)

$(DOCKER_GNMI_TEST)_VERSION = 1.0.0
$(DOCKER_GNMI_TEST)_PACKAGE_NAME = gnmi-test

$(DOCKER_GNMI_TEST)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BULLSEYE)_DBG_IMAGE_PACKAGES)

ifeq ($(INCLUDE_GNMI_TEST), y)
SONIC_DOCKER_IMAGES += $(DOCKER_GNMI_TEST)
SONIC_DOCKER_DBG_IMAGES += $(DOCKER_GNMI_TEST_DBG)
endif


$(DOCKER_GNMI_TEST)_CONTAINER_NAME = gnmi-test
$(DOCKER_GNMI_TEST)_RUN_OPT += --privileged -t
$(DOCKER_GNMI_TEST)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_GNMI_TEST)_RUN_OPT += -v /usr/share/sonic/scripts:/usr/share/sonic/scripts:ro
$(DOCKER_GNMI_TEST)_RUN_OPT += -v /var/run/dbus:/var/run/dbus:rw

$(DOCKER_GNMI_TEST)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)
