# linux kernel package

KVERSION_SHORT = 5.10.65
KVERSION = $(KVERSION_SHORT)-orin
KERNEL_VERSION = 5.10.65
KERNEL_SUBVERSION = orin-1

export KVERSION_SHORT KVERSION KERNEL_VERSION KERNEL_SUBVERSION DTB

LINUX_HEADERS_COMMON = linux-headers-$(KVERSION)_$(KERNEL_VERSION)-$(KERNEL_SUBVERSION)_$(CONFIGURED_ARCH).deb
$(LINUX_HEADERS_COMMON)_SRC_PATH = $(SRC_PATH)/sonic-linux-kernel
SONIC_MAKE_DEBS += $(LINUX_HEADERS_COMMON)

LINUX_KERNEL = linux-image-$(KVERSION)_$(KERNEL_VERSION)-$(KERNEL_SUBVERSION)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(LINUX_HEADERS_COMMON),$(LINUX_KERNEL)))

LINUX_DTB = tegra234-p3701-0000-p3737-0000.dtb
$(eval $(call add_derived_package,$(LINUX_HEADERS_COMMON),$(LINUX_DTB)))

export LINUX_DTB
