# socat packages

ifeq ($(BLDENV),bullseye)
SOCAT_VERSION = 1.7.4.1-3
SOCAT_VERSION_ROOT = 1.7.4.1
else
SOCAT_VERSION = 1.7.3.1-2+deb9u1
SOCAT_VERSION_ROOT = 1.7.3.1
endif

export SOCAT_VERSION SOCAT_VERSION_ROOT

SOCAT = socat_$(SOCAT_VERSION)_$(CONFIGURED_ARCH).deb
$(SOCAT)_SRC_PATH = $(SRC_PATH)/socat
SONIC_MAKE_DEBS += $(SOCAT)
