#!/bin/bash

. /usr/local/share/buildinfo/scripts/buildinfo_base.sh
[ -z $REAL_COMMAND ] && REAL_COMMAND=/usr/bin/curl

# Use --retry option for curl.
# --retry - If a transient error is returned when curl tries to perform a
# transfer, it will retry this number of times before giving up. Transient error
# means either: a timeout, an FTP 4xx response code or an HTTP 408, 429, 500,
# 502, 503 or 504 response code.
REAL_COMMAND="$REAL_COMMAND --retry 5" download_packages "$@"
