steps:
- script: |
    set -x
    # kill daemon process
    ps $(cat /tmp/azp_daemon_kill_docker_pid)
    sudo kill $(cat /tmp/azp_daemon_kill_docker_pid)
    rm /tmp/azp_daemon_kill_docker_pid

    if sudo [ -f /var/run/march/docker.pid ] ; then
        pid=`sudo cat /var/run/march/docker.pid` ; sudo kill $pid
    fi
    sudo rm -f /var/run/march/docker.pid
    sudo rm -rf /data/march/docker

    # clean native docker build
    if sudo [ -f dockerfs/var/run/docker.pid ] ; then
        pid=`sudo cat dockerfs/var/run/docker.pid` ; sudo kill $pid
    fi
    sudo rm -rf $(ls -A1)
  condition: always()
  displayName: "Clean Workspace"
