# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# Build and push sonic-slave-[buster|jessie|stretch] images for amd64/armhf/arm64
resources:
  repositories:
  - repository: buildimage
    type: github
    name: sonic-net/sonic-buildimage
    ref: master
    endpoint: sonic-net

schedules:
- cron: "0 8 * * *"
  branches:
    include:
    - master
    - 202012
  always: true

trigger: none
pr:
  branches:
    include:
    - master
  paths:
    include:
    - sonic-slave-jessie
    - sonic-slave-stretch
    - sonic-slave-buster
    - sonic-slave-bullseye
    - .azure-pipelines

parameters:
- name: 'dists'
  type: object
  default:
  - bullseye
  - buster
  - stretch

stages:
- stage: Build
  jobs:
  - ${{ each dist in parameters.dists }}:
    - ${{ if contains(variables['Build.DefinitionName'], dist) }}:
      - template: docker-sonic-slave-template.yml
        parameters:
          pool: sonicbld-arm64
          arch: arm64
          dist: ${{ dist }}
