steps:
- bash: |
    (
      while true
      do
        sleep 120
        now=$(date +%s)
        pids=$(ps -C docker-buildx -o pid,etime,args | grep "docker-buildx buildx build" | awk '{print $1}')
        for pid in $pids
        do
          start_ticks=$(awk '{print $22}' /proc/$pid/stat)
          boot_time=$(awk '/btime/ {print $2}' /proc/stat)
          hertz=$(getconf CLK_TCK)
          start_time=$((boot_time + start_ticks / hertz))
          ts=$(date -d "@$((now - start_time))" +%s)

          if [[ $ts -gt $(DOCKER_BUILD_TIMEOUT) ]]; then
            echo =========== $(date +%F%T) $time_s &>> target/daemon.log
            ps -p $pid -o pid,etime,args ww &>> target/daemon.log
            sudo kill $pid
          fi
        done
      done
    ) &
    daemon_pid=$!
    ps $daemon_pid
    echo $daemon_pid >> /tmp/azp_daemon_kill_docker_pid
  displayName: start daemon to kill hang docker
